### ISSUE TITLE
[WARNING] Virus Detected

### ISSUE THREAD

**Issue by OnlyHardOfficial** [elmoiv/elmocut#28]
**Describe the bug**
Its not a bug. Its a safety measure
https://www.virustotal.com/gui/file/6d85830c37a83471670bd10fdc03a1556a25d72ed73f3863dd3a882ba1d7a3e2
https://www.google.com/search?q=TrojanSpy.Python.ah&sourceid=chrome&ie=UTF-8

**To Reproduce**
1. Go to 'Your Repo'
2.Download it
3. Analize it via "VirusTotal"
4. Detect what kinda virus its have inside 

Expexted to be a open source tool, and you got infected with a tool that sends vital information to a hacker .!.

**Comment by elmoiv** [comment]
This is a false-positive due to PyInstaller pre-compiled binaries during build process. See [Pyinstaller False-Positive Issues](https://github.com/pyinstaller/pyinstaller/issues?q=label%3Aantivirus-false-positives)

You can also build elmoCut from source yourself and it will give you the same result at VirusTotal.
