### ISSUE TITLE
[False Positive] Windows Defender

### ISSUE THREAD

**Issue by etherealxx** [elmoiv/elmocut#55]
**To Reproduce**
Install it in latest windows 11 with Windows Defender turned on.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/64251396/220878335-b5397992-133d-4070-b1f4-8a12d03a861b.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Chrome (latest)

**Comment by elmoiv** [comment]
elmoCut is a free and non-signed software because digital signature requires paying money to verify apps on Microsoft Windows.

The `restart.exe` code is for restarting elmoCut app once interface is changed by the user.

You can check it form here:
https://github.com/elmoiv/elmocut/blob/main/src/tools/restart.c

```c
#include <stdlib.h>
#include <windows.h>

int main()
{
    // Hide Console Window
    ShowWindow(GetConsoleWindow(), SW_HIDE);
    
    // Start elmocut.exe in a detached process
    system("start \"\" elmocut");
    return 0;
}
```

If you're still worried about elmoCut, you can compile it yourself and have your own executable version.

Have a nice day!

**Comment by elmoiv** [comment]
Thanks for the notice. Will add it ASAP
